language: python
python:
  - "3.5"
env:
  - OBABEL_VERSION=2-4-1
  - OBABEL_VERSION=2-3-2
addons:
  apt:
    packages:
    - cmake
    - build-essential
    - swig
before_install:
  - sudo apt-get install libeigen3-dev
  - cd /home/travis
  - if [ ! -d "openbabel/.git" ]; then git clone https://github.com/openbabel/openbabel.git; fi
  - cd openbabel
  - ls -la
  - git checkout openbabel-$OBABEL_VERSION
  - if [ ! -d "build-$OBABEL_VERSION" ]; then mkdir build-$OBABEL_VERSION; fi
  - cd build-$OBABEL_VERSION
  - cmake -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON -DCMAKE_INSTALL_PREFIX=/home/travis/.local/ ..
  - make -j2
  - sudo make install
  - sudo ldconfig
  - ls -laR /home/travis/.local/lib
  - export PYTHONPATH=/home/travis/.local/lib/python*/site-packages
  - echo $PYTHONPATH
  - echo $PATH
install:
 - cd $TRAVIS_BUILD_DIR
 - pip install .
 - pip install -r test-requirements.txt
script: py.test tests