language: python
python:
  - "3.5"
env:
  - OBABEL_VERSION=2-4-1
  - OBABEL_VERSION=2-3-2
addons:
  apt:
    packages:
    - cmake
    - build-essential
    - swig
before_install:
  - sudo apt-get install libeigen3-dev
  - cd /home/travis
  - git clone https://github.com/openbabel/openbabel.git
  - cd openbabel
  - git checkout openbabel-$OBABEL_VERSION
  - mkdir build-$OBABEL_VERSION
  - cd build-$OBABEL_VERSION
  - cmake -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON -DCMAKE_INSTALL_PREFIX=/home/travis/virtualenv/python* ..
  - make -j2
  - sudo make install
  - sudo ldconfig
  - export PYTHONPATH=/home/travis/virtualenv/python*/lib/python*/site-packages
  - echo $PYTHONPATH
  - echo $PATH
install:
 - cd $TRAVIS_BUILD_DIR
 - pip install .
 - pip install -r test-requirements.txt
script: py.test tests